# -*- coding: utf-8 -*-
"""Laboratorio 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12C7FflUAGFP-MzYfI5wR3O6r0XhOlcFR

# 1. Carga el dataset.
"""

import pandas as pd

# Montar Google Drive si el archivo está allí
#from google.colab import drive
#drive.mount('/content/drive')

# Cargar el archivo CSV (ajusta la ruta si está en tu Drive)
df = pd.read_csv('data/Reviews_reducido.csv')

git commit -m "Subir archivo CSV"
git push origin main


# Ver las primeras filas
df.head()

"""# Seleccionar columnas importantes"""

df = df[['Text', 'Score']]

"""# Crear columna de sentimiento


"""

def sentimiento(score):
    return 'Positivo' if score >= 4 else 'Negativo'

df['Sentimiento'] = df['Score'].apply(sentimiento)

"""# Mostrar distribución de sentimientos"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Sentimiento', data=df)
plt.title("Distribución de Sentimientos")
plt.show()

"""# 2. Preguntas rápidas para reflexión:
¿Qué tipo de datos encontramos en las columnas?

¿Cuál es la proporción de reseñas positivas vs. negativas?
"""

df['Sentimiento'].value_counts(normalize=True)

"""# 3. Preprocesamiento y vectorización
🔹 Dividir los datos
"""

from sklearn.model_selection import train_test_split

X = df['Text']
y = df['Sentimiento']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""🔹 Vectorizar el texto"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

"""# 4. Reflexión guiada
¿Qué hace el CountVectorizer?

CountVectorizer es como una herramienta que convierte las palabras en números. Las computadoras no entienden palabras, pero sí entienden números. Entonces, CountVectorizer toma todo el texto . y cuenta cuántas veces aparece cada palabra. Luego pone esos números en una tabla para que el modelo pueda aprender de ellos. Por ejemplo, si alguien dice “excelente producto”, CountVectorizer guarda que “excelente” y “producto” aparecieron 1 vez.

¿Por qué dividimos los datos en conjuntos de entrenamiento y prueba?

Es como cuando estudias para un examen: primero practicas con ejercicios (entrenamiento) y luego haces una prueba para ver si aprendiste (prueba). Aquí hacemos lo mismo con el modelo. Usamos una parte de los datos para enseñarle (entrenamiento) y otra parte diferente para ver si aprendió bien (prueba). Así evitamos que solo se “memorice” las respuestas y comprobamos si puede adivinar correctamente con datos nuevos.

# 5. Entrenamiento y evaluación del modelo
🔹 Entrenar el modelo
"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

"""🔹 Evaluar el modelo"""

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test_vectorized)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

"""🔹 Probar con texto real"""

ejemplos = ["This product is amazing!", "Worst purchase I've ever made."]
ej_vector = vectorizer.transform(ejemplos)
print(model.predict(ej_vector))

"""# Implementación detallada"""

# Paso 1: Importar CountVectorizer y modelo Naive Bayes
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# Paso 2: Vectorizar el texto
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

# Paso 3: Entrenar modelo Naive Bayes
model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

# Paso 4: Evaluar modelo
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test_vectorized)
print("Precisión del modelo (accuracy):", accuracy_score(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))
